Login
bartosz-kepka/social-media-app pull request #1
Opened 2021-07-19 18:48 UTC by Patrykaca

2021-07-30 23:13 UTC, bartosz-kepka requested changes
fix pls
use http interceptor fot adding authorization header to requests which need it

2021-07-30 23:13 UTC, bartosz-kepka commented on package.json
> +    "vee-validate": "^2.2.15",
I don't see any usages of this library. Remove it. Anyway, for validation use **vuelidate**. Don't forget to run **npm install** later.

2021-07-30 23:13 UTC, bartosz-kepka commented on package.json
> +    "vue-cookies": "^1.7.4",
I don't see any usages of this library. If it's not being used, remove it. Don't forget to run **npm install** later.

2021-07-30 23:13 UTC, bartosz-kepka commented on src/components/global/Navigation.vue
> +      <v-spacer />
Unnecessary spacer

2021-07-30 23:13 UTC, bartosz-kepka commented on src/components/global/Navigation.vue
> +
Unused method

2021-07-30 23:13 UTC, bartosz-kepka commented on src/components/global/Navigation.vue
> +      window.location.reload(true);
Remove comment
If you need to use **window.location.reload(true);** then in most cases something is bugged/broken. Remove it

2021-07-30 23:13 UTC, bartosz-kepka commented on src/locales/en.json
> +
Remove blank line

2021-07-30 23:13 UTC, bartosz-kepka commented on src/locales/en.json
> +    "registerTitle": "Please sign in",
use kebab-case

2021-07-30 23:13 UTC, bartosz-kepka commented on src/locales/pl.json
> +    "registerTitle": "Zarejestruj się",
as above

2021-07-30 23:13 UTC, bartosz-kepka commented on src/main.js
> +
Remove if unsued

2021-07-30 23:13 UTC, bartosz-kepka commented on src/main.js
> +Vue.use(VueCookies);
Remove if unsued

2021-07-30 23:13 UTC, bartosz-kepka commented on src/services/auth-header.js
> +}
Get token from vuex store using getter.
Use localstorage only for storing it between sessions, page refreshes etc. 
Save user info in localstorage when loggin in, clear it when logggin out, read it when app is launching (see main.js  line 33)

2021-07-30 23:13 UTC, bartosz-kepka commented on src/router/index.js
> +)
Fix it pls... It cannot be considered done.
```
const publicRoutes = ['Login', 'Register'];

router.beforeEach(({ name }, from, next) => {
    const isAuthenticated = store.getters['user/isAuthenticated'];
    const toPrivateRoute = !publicRoutes.includes(name);

    if (toPrivateRoute && !isAuthenticated) {
      next({ name: 'Login' });
      return;
    }

    if (!toPrivateRoute && isAuthenticated) {
      next({ name: 'Home' });
      return;
    }

    next();
  },
);
```

2021-07-30 23:13 UTC, bartosz-kepka commented on src/services/auth.service.js
> +const API_URL = 'http://localhost:8080/api/api/auth/';
```suggestion
const baseURL = '/auth';
```

2021-07-30 23:13 UTC, bartosz-kepka commented on src/services/auth.service.js
> +import axios from 'axios';
**take a look at chat.service.js**

```suggestion
import $axios from '@/axios';
```

2021-07-30 23:13 UTC, bartosz-kepka commented on src/services/auth.service.js
> +    login(user) {
```suggestion
    login(credentials) {
```

2021-07-30 23:13 UTC, bartosz-kepka commented on src/services/auth.service.js
> +            })
```suggestion
        const url = `${baseURL}/signin`;
        return axios.post(url, credentials)
```

2021-07-30 23:13 UTC, bartosz-kepka commented on src/services/auth.service.js
> +                    localStorage.setItem('user', JSON.stringify(response.data));
do it in vuex action

2021-07-30 23:13 UTC, bartosz-kepka commented on src/services/auth.service.js
> +    }
clear user info from localstorage in vuex action together with vuex state

2021-07-30 23:13 UTC, bartosz-kepka commented on src/services/auth.service.js
> +        });
```suggestion
        const url = `${baseURL}/signup`;
        return axios.post(url, registrationData);
```

2021-07-30 23:13 UTC, bartosz-kepka commented on src/services/auth.service.js
> +export default new AuthService();
make this service an object and move to http subdirectory
```suggestion
export default AuthService;
```

2021-07-30 23:13 UTC, bartosz-kepka commented on src/services/user.service.js
> +export default new UserService();
remove

2021-07-30 23:13 UTC, bartosz-kepka commented on src/store/auth.module.js
> +    : { status: { loggedIn: false }, user: null };
load user info from localstorage in load-data.js

2021-07-30 23:13 UTC, bartosz-kepka commented on src/store/auth.module.js
> +import AuthService from '../services/auth.service';
dont use relative paths for imports
```suggestion
import AuthService from '@/services/http/auth.service';
```

2021-07-30 23:13 UTC, bartosz-kepka commented on src/store/auth.module.js
> +    }
Move this logic to src/store/modules/user.js. Analyze it and adjust the code above. Delete this file

2021-07-30 23:13 UTC, bartosz-kepka commented on src/store/index.js
> +import { auth } from './auth.module';
this module will be removed

2021-07-30 23:13 UTC, bartosz-kepka commented on src/store/index.js
> +    auth,
this module will be removed

2021-07-30 23:13 UTC, bartosz-kepka commented on src/store/modules/user.js
> +
.

2021-07-30 23:13 UTC, bartosz-kepka commented on src/store/modules/user.js
> +      window.location.reload(true);
remove unused code, dont reaload the app like that

2021-07-30 23:13 UTC, bartosz-kepka commented on src/store/user.js
> +}
no need to define a class

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Login.vue
> +import User from '../store/user';
don't use relative imports

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Login.vue
> +      return this.$store.state.auth.status.loggedIn;
use getter and map it, see ChatConversation.vue line 17

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Login.vue
> +  //  },
remove commented code

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Login.vue
> +      if (!this.$v.name.$dirty) {
not **name** but **password**

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Login.vue
> +      if (!this.$v.name.minLength) {
not **name** but **password**

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Login.vue
> +      if (!this.$v.name.required) {
not **name** but **password**

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Login.vue
> +            }
use vuelidate

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Login.vue
> +      this.loading = true;
mesage loading in vuex store, see src/store/modules/chat.js method at line 99

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Login.vue
> +                this.$store.dispatch('user/setUser', user);
update setUser action from store and dipatch it from login action when user is successfully loggen in

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Login.vue
> +                alert(error.response.data.message);
use https://vuetifyjs.com/en/components/snackbars/

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Login.vue
> +                    error.toString();
display custom message from BE

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Login.vue
> +        if (this.user.username && this.user.password) {
validate with vuelidate

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Login.vue
> +      this.$router.push('/register');
use name
```suggestion
            this.$router.push({name: 'Register'});
```

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Profile.vue
> +    }
route guard should be defined in  src/router/index.js

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Profile.vue
> +    }
use getter

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Profile.vue
> +  </div>
Expand it, give user a possibility to edit his information

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Register.vue
> +    },
all of them validate only name

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Register.vue
> +    // },
remove

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Register.vue
> +      return this.$store.state.auth.status.loggedIn;
use getter and map it

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Register.vue
> +      this.submitted = true;
what is that for?

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Register.vue
> +      this.$validator.validate().then(isValid => {
use vuelidate

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Register.vue
> +        console.log('chuj');
xd

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Register.vue
> +                this.successful = true;
what is that for?

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Register.vue
> +                this.handleLogin();
redirect to login page

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Register.vue
> +                this.message = data.message;
show a notification using notification module of vuex store, see usage at chat module

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Register.vue
> +                alert(error.response.data.message);
use snackbar from vuetify

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Register.vue
> +    },
remove

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Register.vue
> +      message: '',
what is that for? where are you using it?

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Register.vue
> +  },
define validations for input fields here

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Register.vue
> +  },
login?

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Register.vue
> +        </v-btn>
add button for going back bo login page

2021-07-30 23:13 UTC, bartosz-kepka commented on src/views/Login.vue
>    validations: {
define validations for input fields here

2021-08-25 13:03 UTC, Patrykaca commented on package.json
> +    "vee-validate": "^2.2.15",
after deleting login button stops working

2021-08-25 13:03 UTC, Patrykaca commented on package.json
> +    "vue-cookies": "^1.7.4",
after deleting login button stops working

2021-08-25 13:15 UTC, Patrykaca commented on src/store/auth.module.js
> +import AuthService from '../services/auth.service';
Cannot install Node.js module: "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" install @/services --save-dev

2021-08-26 11:57 UTC, bartosz-kepka commented on package.json
> +    "vee-validate": "^2.2.15",
My bad comment, this library is used for validation while logging in. Please replace its usage with vuelidate as mentioned here: https://github.com/bartosz-kepka/social-media-app/pull/1/files#r680252017

2021-08-26 11:57 UTC, bartosz-kepka commented on package.json
> +    "vue-cookies": "^1.7.4",
Same as above

2021-08-26 13:16 UTC, Patrykaca commented on src/store/modules/user.js
> +      window.location.reload(true);
i don't have any idea how to log out a different way properly, without it cookies are not removed (I think)

2021-08-26 13:57 UTC, Patrykaca commented on src/views/Register.vue
> +        </v-btn>
done

2021-08-27 15:58 UTC, bartosz-kepka commented on src/store/auth.module.js
> +import AuthService from '../services/auth.service';
It's not a module to install. It's a path relative to src directory: https://stackoverflow.com/a/42753045/10876483

2021-08-27 16:20 UTC, bartosz-kepka commented on src/store/modules/user.js
> +      window.location.reload(true);
User-specific info like authentication token and roles should be stored in vuex store and local storage. Local storage should be a copy of info stored in vuex. We consider a user to be loggen in when there are some information saved in vuex store so "to log out" means to clear all user info from both vuex store and local storage. A copy of user info should be stored in local storage so that we can load it after page refresh or when opening a website later (local storage is persistent while every time we open an app we create a new instance of vuex store this is empty). Create a getter which  would indicate whether some user is logged in (token, login, roles etc. are saved in vuex store).
Take a look here: https://github.com/bartosz-kepka/social-media-app/pull/1#discussion_r680227894 -**user/isAuthenticated** getter is used to specify if user some user is logged in. 

To sum up:
1. Store currently logged in user info in vuex
2. Create a getter which will indicate whether some user is logged in
3. When "Log out" button (or similar) is clicked then dispatch an action that will remove user info from vuex store (from local storage too as it should be a copy)
4. Because we cleared user info the getter should indicate that there is no logged in user - e.g. getter should return false now (instead of true)
5. Redirect to login page

2021-08-31 23:13 UTC, bartosz-kepka approved these changes

2021-08-31 23:15 UTC, merged